### PR TITLE
Added nightly to tests;  it fails if it does not have access to nightly

### PR DESCRIPTION
**Pull request by jessberg**
The failing tests were failing because in order to compile they needed the nightly toolchain.  I just added it to a couple commands.

### CODE REVIEW

**Comment by fruffy** [comment]
I do not think this will work

**Comment by jessberg** [comment]
> I do not think this will work

Why is that?  It is passing when I run it locally.

**Comment by fruffy** [comment]
These are the old modules, which still all pass. I would use the branch I have opened, with reference to the new changes in the submodules. Also nightly is already the default here https://github.com/dyn-tracing/tracing_env/blob/master/tools/setup_sim.sh#L15

**Comment by jessberg** [comment]
> These are the old modules, which still all pass. I would use the branch I have opened, with reference to the new changes in the submodules. Also nightly is already the default here https://github.com/dyn-tracing/tracing_env/blob/master/tools/setup_sim.sh#L15

Makes sense.  I will close this then

**Pull request closed without merging**
